name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "a build demo"
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Test step
         run: echo "running test"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
       - name: deploy the app
         run: echo "deploy test job"
