name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "a build demo"
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Test step
         run: echo"running"
