name: Hello world
on: workflow_dispatch
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
          - name: Hello steps
            run: |  
              echo "this is line one"
              echo "this is line two"
